[package]
name = "sf-api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.1"
base64 = "0.21"
chrono = "0.4"
fastrand = "2.0"
log = "0.4"
num = "0.4"
num-bigint = { version = "0.4" }
num-derive = "0.4"
num-traits = "0.2"
once_cell = "1.18"
openssl = "0.10"
ouroboros = "0.18"
reqwest = { version = "0.11", features = ["gzip", "deflate", "brotli"] }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
strum = { version = "0.25", features = ["strum_macros", "derive"] }
tokio = "1.33"
url = "2.4"

[features]
default = ["sso", "serde"]
sso = ["dep:serde", "dep:serde_json"]
serde = ["dep:serde", "num-bigint/serde", "chrono/serde"]
